---
name: festival-dev
services:
  db:
    image: postgres:16@sha256:c872a9645522f1f4fe8addb175aae9941e9291db4c20589cbabbc7ff188b279d
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db-data:
